# Generated by Django 5.0.3 on 2024-04-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='imagen',
            new_name='imagen_de_perfil',
        ),
    ]
